### ISSUE TITLE
bin/rails test test/models/tweet_controller_test.rbの結果

### ISSUE THREAD

**Issue by suminofu0829** [suminofu0829/tweet_fav_and_rt_count.app#74]
```
-> % bin/rails test test/models/tweet_controller_test.rb
Running via Spring preloader in process 46554
/Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require': cannot load such file -- /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/test/models/tweet_controller_test.rb (LoadError)
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/test_unit/runner.rb:50:in `block in load_tests'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/test_unit/runner.rb:50:in `each'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/test_unit/runner.rb:50:in `load_tests'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/test_unit/runner.rb:39:in `run'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/commands/test/test_command.rb:33:in `perform'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/command/base.rb:65:in `perform'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/command.rb:46:in `invoke'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/railties-5.2.2/lib/rails/commands.rb:18:in `<main>'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/bin/rails:9:in `<main>'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `block in load'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by suminofu0829** [comment]
```
-> % bin/rails test test/controllers/tweet_controller_test.rb
Running via Spring preloader in process 46572
Run options: --seed 29708

# Running:

E

Error:
TweetControllerTest#test_should_get_index:
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'app_db.ranks' doesn't exist: SHOW FULL FIELDS FROM `ranks`



bin/rails test test/controllers/tweet_controller_test.rb:4



Finished in 0.282873s, 3.5352 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by suminofu0829** [comment]
```
-> % bin/rails test test/controllers/tweet_controller_test.rb
Running via Spring preloader in process 46618
Run options: --seed 50828

# Running:

F

Failure:
TweetControllerTest#test_should_get_index [/Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/test/controllers/tweet_controller_test.rb:6]:
Expected response to be a <2XX: success>, but was a <302: Found> redirect to <http://www.example.com/users/sign_in>
Response body: <html><body>You are being <a href="http://www.example.com/users/sign_in">redirected</a>.</body></html>


bin/rails test test/controllers/tweet_controller_test.rb:4



Finished in 1.863447s, 0.5366 runs/s, 0.5366 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by suminofu0829** [comment]
```
-> % bin/rails test test/controllers/tweet_controller_test.rb
Running via Spring preloader in process 46682
DEPRECATION WARNING: [Devise] including `Devise::TestHelpers` is deprecated and will be removed from Devise.
For controller tests, please include `Devise::Test::ControllerHelpers` instead.
 (called from include at /Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/test/controllers/tweet_controller_test.rb:5)
Run options: --seed 53700

# Running:

E

Error:
TweetControllerTest#test_should_get_index:
NoMethodError: undefined method `env' for nil:NilClass



bin/rails test test/controllers/tweet_controller_test.rb:11



Finished in 0.590696s, 1.6929 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by suminofu0829** [comment]
```
-> % bin/rails test test/controllers/tweet_controller_test.rb
Running via Spring preloader in process 46890
Run options: --seed 59316

# Running:

E

Error:
TweetControllerTest#test_should_get_index:
ActionController::UrlGenerationError: No route matches {:action=>"http://test.host/tweet/index", :controller=>"tweet"}
    test/controllers/tweet_controller_test.rb:12:in `block in <class:TweetControllerTest>'


bin/rails test test/controllers/tweet_controller_test.rb:8



Finished in 0.629574s, 1.5884 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by suminofu0829** [comment]
```
-> % bin/rails test test/controllers/tweet_controller_test.rb
Running via Spring preloader in process 47071
Run options: --seed 42068

# Running:

F

Failure:
TweetControllerTest#test_should_get_index [/Users/kazuyasumino/Documents/ruby_on_rails/environment/tweet_fav_and_rt_count/test/controllers/tweet_controller_test.rb:13]:
Expected response to be a <2XX: success>, but was a <302: Found> redirect to <http://test.host/users/sign_in>
Response body: <html><body>You are being <a href="http://test.host/users/sign_in">redirected</a>.</body></html>


bin/rails test test/controllers/tweet_controller_test.rb:8



Finished in 2.139530s, 0.4674 runs/s, 0.4674 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by suminofu0829** [comment]
```
-> % bin/rails test test/controllers/tweet_controller_test.rb
Running via Spring preloader in process 47160
Run options: --seed 63970

# Running:

.

Finished in 12.862793s, 0.0777 runs/s, 0.0777 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```
